
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - bash: echo Build first Job
  - job: Job2
    steps:
    - bash: echo Building second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Deploying first Job
  - job: Job2
    steps:
    - bash: echo Deploying second Job
- stage: ProdDeploy
  jobs:
  - job: job1
    steps:
    - script: echo Deploying to Prod
      displayName: 'Prod Deploy'



